---
image: h.eefocus.tech/devops/docker/ansible:latest

variables:
  CI_DEBUG_TRACE: "false"
  DOCKER_DRIVER: overlay2
  REMOTE_SSH: ssh aa92
  REMOTE_SERVER_ALIAS: aa92
  SSH_HOME_DIR: "$HOME/.ssh/"
  DEPLOY_PATH: "/opt/vhosts/wx-spider/src/"

before_script:
  - mkdir -p ${SSH_HOME_DIR}
  - echo "$SSH_KEY" > ${SSH_HOME_DIR}id_rsa
  - echo "$SSH_CONFIG" > ${SSH_HOME_DIR}config
  - chmod 600 ${SSH_HOME_DIR}id_rsa ${SSH_HOME_DIR}config




.common_runner: &common_runner
  retry: 2
  only:
    - master
  tags:
    - docker


stages:
  - build


wx-crawler:
  <<: *common_runner
  stage: build
  script:
    - pwd; id


